<a href="https://colab.research.google.com/github/Anjasfedo/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentlas

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensors

Create Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get python int
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
print(TENSOR[0][0])

tensor([1, 2, 3])


### Random tensors

Random tensort important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data => update random numbers -> look at data -> update random numbers`

In [18]:
# Create random tensor with size of (3, 4)
rand_tensor = torch.rand(3, 4)
print(rand_tensor.shape)
print(rand_tensor.ndim)
rand_tensor

torch.Size([3, 4])
2


tensor([[0.0630, 0.7059, 0.7161, 0.6427],
        [0.8817, 0.0744, 0.0977, 0.1919],
        [0.5404, 0.6215, 0.8515, 0.8726]])

In [19]:
# Create random tensor with simmiliar shape of an image tensor
rand_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color channels(rgb))
print(rand_image_size_tensor.shape, rand_image_size_tensor.ndim)
rand_image_size_tensor

torch.Size([224, 224, 3]) 3


tensor([[[0.7994, 0.5686, 0.5896],
         [0.6601, 0.0055, 0.6121],
         [0.8015, 0.3557, 0.9008],
         ...,
         [0.6928, 0.8963, 0.1011],
         [0.2599, 0.1205, 0.9554],
         [0.0459, 0.8285, 0.9250]],

        [[0.5165, 0.9380, 0.3577],
         [0.8656, 0.2003, 0.1738],
         [0.3683, 0.2938, 0.4926],
         ...,
         [0.5770, 0.1371, 0.5610],
         [0.5361, 0.1356, 0.0805],
         [0.9341, 0.7935, 0.3528]],

        [[0.3823, 0.3908, 0.5440],
         [0.8406, 0.7740, 0.9836],
         [0.8684, 0.9890, 0.6258],
         ...,
         [0.3932, 0.1756, 0.3503],
         [0.0909, 0.9803, 0.2919],
         [0.4788, 0.6962, 0.1738]],

        ...,

        [[0.4869, 0.5589, 0.9906],
         [0.3854, 0.7680, 0.5225],
         [0.4294, 0.1118, 0.3938],
         ...,
         [0.9763, 0.5939, 0.5231],
         [0.0291, 0.8448, 0.6243],
         [0.0321, 0.2506, 0.9219]],

        [[0.6914, 0.1733, 0.4858],
         [0.5307, 0.8842, 0.7756],
         [0.

### Zeros & Ones

In [20]:
# Create tensor of all zeros
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create tensor of all ones
ones_tensor = torch.ones(3, 4)
print(ones_tensor.dtype)
ones_tensor

torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensor and tensor-like

In [22]:
# Use torch.range
torch.range(0, 10)

<ipython-input-22-bfd1d11818ee>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Create tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

it dealing with precision of computing & memory manajement

**Note:** Tensor datatypes is one of 3 big error
1. Tensor no right datatype
2. Tensor not rigth shape
3. Tensor not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # data type of tensor, device tensor on, is track gradient
float_32_tensor.dtype

torch.float32

In [26]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

### Get information of tensor

1. Tensor no right datatype - `tensor.dtype`
2. Tensor not rigth shape = `tensor.shape`
3. Tensor not on the right device - `tensor.device`

In [30]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9200, 0.6645, 0.1224, 0.2881],
        [0.6579, 0.7599, 0.0966, 0.5760],
        [0.0276, 0.8280, 0.5861, 0.9510]])

In [31]:
# Find details of some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [32]:
# tensor add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# tensor multiply by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# Pytorch built-in function
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

with two way to perform it

1. element-wise multiplication
2. matrix multiplication (dot product)

there two main rules of matrix multiplication
1. **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. resulting matrix has the shape of **outer dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [36]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"equal to {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal to tensor([1, 4, 9])


In [37]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor @ tensor

tensor(14)

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
%%time
val = 0
for i in range (len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(14)
CPU times: user 2.28 ms, sys: 0 ns, total: 2.28 ms
Wall time: 6.34 ms


In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 80 µs, sys: 14 µs, total: 94 µs
Wall time: 98.7 µs


tensor(14)

### most common errors of shape error

In [47]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.matmul == torch.mm == @ operation

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix tensor shape issues, we can manipulate shape of one of tensor with **transpose**

a **transpose** switches the axes or dimensions of a given tensor

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
# matrix multiplication work

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [52]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [53]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# find mean - note: torch.mean require float32 dytpe
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [57]:
# find position index of min value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [58]:
# find position index of max value
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, staking, squeezing and unsqueesing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a virw of input tensor but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [59]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# Changing z will changes x (because view share same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
# Squeeze tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# Unsqueeze tensor
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [67]:
# Permute tensor
x_original = torch.rand(size=(244, 244, 3))
x_original, x_original.shape

(tensor([[[0.5360, 0.0746, 0.2687],
          [0.2142, 0.6334, 0.9490],
          [0.5503, 0.2751, 0.2474],
          ...,
          [0.4833, 0.8523, 0.6206],
          [0.6696, 0.4092, 0.8582],
          [0.9154, 0.2171, 0.9576]],
 
         [[0.7144, 0.8958, 0.3007],
          [0.7021, 0.3402, 0.7969],
          [0.3889, 0.4815, 0.9744],
          ...,
          [0.3012, 0.2124, 0.4541],
          [0.9375, 0.9260, 0.0595],
          [0.3433, 0.1365, 0.1851]],
 
         [[0.3213, 0.1937, 0.0927],
          [0.3116, 0.4659, 0.3372],
          [0.4488, 0.9776, 0.4105],
          ...,
          [0.0683, 0.0436, 0.3414],
          [0.1043, 0.5810, 0.5748],
          [0.8636, 0.5067, 0.2596]],
 
         ...,
 
         [[0.1957, 0.8900, 0.1019],
          [0.3315, 0.2473, 0.5191],
          [0.0443, 0.7186, 0.7179],
          ...,
          [0.9148, 0.2276, 0.8797],
          [0.5510, 0.8249, 0.5037],
          [0.2917, 0.9416, 0.3297]],
 
         [[0.7189, 0.6438, 0.3378],
          [0

In [68]:
x_permuted = torch.permute(x_original, dims=(2, 0, 1))
x_permuted, x_permuted.shape

(tensor([[[0.5360, 0.2142, 0.5503,  ..., 0.4833, 0.6696, 0.9154],
          [0.7144, 0.7021, 0.3889,  ..., 0.3012, 0.9375, 0.3433],
          [0.3213, 0.3116, 0.4488,  ..., 0.0683, 0.1043, 0.8636],
          ...,
          [0.1957, 0.3315, 0.0443,  ..., 0.9148, 0.5510, 0.2917],
          [0.7189, 0.4973, 0.0281,  ..., 0.4428, 0.6723, 0.9152],
          [0.0317, 0.6547, 0.5451,  ..., 0.8501, 0.0438, 0.8274]],
 
         [[0.0746, 0.6334, 0.2751,  ..., 0.8523, 0.4092, 0.2171],
          [0.8958, 0.3402, 0.4815,  ..., 0.2124, 0.9260, 0.1365],
          [0.1937, 0.4659, 0.9776,  ..., 0.0436, 0.5810, 0.5067],
          ...,
          [0.8900, 0.2473, 0.7186,  ..., 0.2276, 0.8249, 0.9416],
          [0.6438, 0.3076, 0.6983,  ..., 0.0306, 0.3968, 0.5522],
          [0.6529, 0.7426, 0.1840,  ..., 0.4201, 0.0322, 0.7196]],
 
         [[0.2687, 0.9490, 0.2474,  ..., 0.6206, 0.8582, 0.9576],
          [0.3007, 0.7969, 0.9744,  ..., 0.4541, 0.0595, 0.1851],
          [0.0927, 0.3372, 0.4105,  ...,

In [69]:
# Permuted share same memory
x_original[0, 0, 0] = 1

In [70]:
x_permuted[0, 0, 0]

tensor(1.)

### Indexing (select data from tensors index position)

indexing with PyTorch = indexing with NumPy

In [71]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [74]:
x[0][2][0]

tensor(7)

In [75]:
# ":" to select all of target dimension
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch & NumPy

NumPy scientific Python numerical computing library

PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTorch to NumPy -> `torch.Tensor.numpy()`

In [84]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # PyTorch get NumPy datatype of float64, convert it with .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [86]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [90]:
# Change value of array, what will heppen on tensor

array = array + 1
array, tensor

(array([ 5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [92]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
numpy_tensor.dtype

dtype('float32')

In [94]:
# Change tensor, what heppen to NumPy Tensor

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

try to take random out of random

neural network learn:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again....

to reduce the randomness on neural network and PyTorch, there is **random seed**

random seed does flavour the randomness

https://pytorch.org/docs/stable/notes/randomness.html

In [100]:
torch.rand(3, 3)

tensor([[0.3025, 0.5803, 0.6490],
        [0.3097, 0.0931, 0.7950],
        [0.7575, 0.9729, 0.4942]])

In [102]:
import torch

# create two random

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8411, 0.9819, 0.4284, 0.4490],
        [0.4327, 0.0929, 0.2389, 0.5946],
        [0.4842, 0.5128, 0.4288, 0.9523]])
tensor([[0.4203, 0.0306, 0.3007, 0.9601],
        [0.6821, 0.8298, 0.7435, 0.8850],
        [0.7844, 0.7496, 0.2999, 0.8072]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [110]:
# random but reproducable tensors

# set the random seed, on notebook random seed only work once
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
