<a href="https://colab.research.google.com/github/Anjasfedo/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentlas

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensors

Create Tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get python int
scalar.item()

7

In [7]:
scalar.shape

torch.Size([])

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
print(TENSOR[0][0])

tensor([1, 2, 3])


### Random tensors

Random tensort important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data => update random numbers -> look at data -> update random numbers`

In [19]:
# Create random tensor with size of (3, 4)
rand_tensor = torch.rand(3, 4)
print(rand_tensor.shape)
print(rand_tensor.ndim)
rand_tensor

torch.Size([3, 4])
2


tensor([[0.8496, 0.2752, 0.6398, 0.0499],
        [0.3481, 0.2699, 0.4781, 0.9874],
        [0.6837, 0.7008, 0.8599, 0.7084]])

In [20]:
# Create random tensor with simmiliar shape of an image tensor
rand_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color channels(rgb))
print(rand_image_size_tensor.shape, rand_image_size_tensor.ndim)
rand_image_size_tensor

torch.Size([224, 224, 3]) 3


tensor([[[0.3788, 0.8695, 0.8960],
         [0.7416, 0.4368, 0.3481],
         [0.0625, 0.0511, 0.7676],
         ...,
         [0.6754, 0.8171, 0.9327],
         [0.7353, 0.5697, 0.6272],
         [0.7789, 0.7332, 0.5900]],

        [[0.9101, 0.2375, 0.9879],
         [0.1420, 0.0060, 0.0114],
         [0.8207, 0.7568, 0.6032],
         ...,
         [0.3826, 0.1625, 0.0629],
         [0.5956, 0.1658, 0.7695],
         [0.6281, 0.9029, 0.3438]],

        [[0.6993, 0.6515, 0.5752],
         [0.8808, 0.7580, 0.0337],
         [0.0226, 0.4677, 0.1297],
         ...,
         [0.5315, 0.0441, 0.7334],
         [0.4865, 0.8757, 0.4313],
         [0.1866, 0.0476, 0.8744]],

        ...,

        [[0.2935, 0.8756, 0.3485],
         [0.5802, 0.8896, 0.9930],
         [0.3613, 0.7676, 0.0836],
         ...,
         [0.8971, 0.1294, 0.5056],
         [0.6435, 0.3781, 0.1015],
         [0.5577, 0.3595, 0.7699]],

        [[0.3078, 0.5621, 0.8151],
         [0.9289, 0.4982, 0.5053],
         [0.

### Zeros & Ones

In [21]:
# Create tensor of all zeros
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create tensor of all ones
ones_tensor = torch.ones(3, 4)
print(ones_tensor.dtype)
ones_tensor

torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensor and tensor-like

In [23]:
# Use torch.range
torch.range(0, 10)

<ipython-input-23-bfd1d11818ee>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Create tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

it dealing with precision of computing & memory manajement

**Note:** Tensor datatypes is one of 3 big error
1. Tensor no right datatype
2. Tensor not rigth shape
3. Tensor not on the right device

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # data type of tensor, device tensor on, is track gradient
float_32_tensor.dtype

torch.float32

In [27]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

### Get information of tensor

1. Tensor no right datatype - `tensor.dtype`
2. Tensor not rigth shape = `tensor.shape`
3. Tensor not on the right device - `tensor.device`

In [31]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7033, 0.5720, 0.5929, 0.7819],
        [0.2479, 0.5353, 0.3666, 0.3493],
        [0.1322, 0.4235, 0.9701, 0.2555]])

In [32]:
# Find details of some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [33]:
# tensor add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# tensor multiply by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Pytorch built-in function
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

with two way to perform it

1. element-wise multiplication
2. matrix multiplication (dot product)

there two main rules of matrix multiplication
1. **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. resulting matrix has the shape of **outer dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [39]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"equal to {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal to tensor([1, 4, 9])


In [40]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor @ tensor

tensor(14)

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [45]:
%%time
val = 0
for i in range (len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(14)
CPU times: user 2.79 ms, sys: 0 ns, total: 2.79 ms
Wall time: 2.59 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 486 µs, sys: 0 ns, total: 486 µs
Wall time: 393 µs


tensor(14)

### most common errors of shape error

In [64]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.matmul == torch.mm == @ operation

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [60]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix tensor shape issues, we can manipulate shape of one of tensor with **transpose**

a **transpose** switches the axes or dimensions of a given tensor

In [68]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [67]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [69]:
# matrix multiplication work

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [90]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [91]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [73]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [80]:
# find mean - note: torch.mean require float32 dytpe
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [82]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [93]:
# find position index of min value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [92]:
# find position index of max value
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, staking, squeezing and unsqueesing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a virw of input tensor but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [109]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [110]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
# Changing z will changes x (because view share same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [133]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [159]:
# Squeeze tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [162]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [172]:
# Unsqueeze tensor
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [189]:
# Permute tensor
x_original = torch.rand(size=(244, 244, 3))
x_original, x_original.shape

(tensor([[[5.5139e-01, 5.4917e-01, 2.9967e-01],
          [7.1164e-01, 1.6570e-01, 6.5458e-01],
          [1.2430e-02, 8.0596e-01, 6.5615e-01],
          ...,
          [6.2897e-01, 5.0622e-01, 3.8975e-01],
          [9.3284e-01, 9.8651e-01, 9.0851e-01],
          [1.2042e-01, 9.3901e-01, 8.5439e-01]],
 
         [[4.5571e-01, 8.7209e-01, 6.9348e-01],
          [6.0095e-01, 8.9824e-01, 1.4249e-01],
          [1.9999e-01, 7.6383e-01, 7.4220e-01],
          ...,
          [3.1915e-01, 5.5565e-01, 4.9330e-01],
          [1.3685e-01, 7.8321e-04, 1.1278e-01],
          [9.7628e-01, 6.0651e-01, 8.8795e-01]],
 
         [[6.5031e-01, 6.5072e-01, 3.2199e-01],
          [4.0113e-01, 1.7295e-01, 4.7113e-01],
          [5.1394e-01, 6.3266e-01, 9.7680e-01],
          ...,
          [7.8326e-01, 2.2064e-01, 7.8378e-01],
          [8.3398e-01, 6.5813e-01, 9.8231e-01],
          [1.2885e-01, 7.6721e-01, 3.1772e-01]],
 
         ...,
 
         [[3.3745e-01, 5.4600e-02, 6.8071e-01],
          [4.7039e

In [190]:
x_permuted = torch.permute(x_original, dims=(2, 0, 1))
x_permuted, x_permuted.shape

(tensor([[[5.5139e-01, 7.1164e-01, 1.2430e-02,  ..., 6.2897e-01,
           9.3284e-01, 1.2042e-01],
          [4.5571e-01, 6.0095e-01, 1.9999e-01,  ..., 3.1915e-01,
           1.3685e-01, 9.7628e-01],
          [6.5031e-01, 4.0113e-01, 5.1394e-01,  ..., 7.8326e-01,
           8.3398e-01, 1.2885e-01],
          ...,
          [3.3745e-01, 4.7039e-01, 2.1854e-01,  ..., 2.2646e-01,
           8.3308e-01, 2.1899e-02],
          [1.8142e-01, 8.6644e-01, 2.2324e-01,  ..., 8.8548e-01,
           3.5052e-01, 6.3957e-01],
          [6.6018e-01, 1.8683e-01, 8.2845e-01,  ..., 7.4148e-01,
           4.1493e-01, 4.8103e-01]],
 
         [[5.4917e-01, 1.6570e-01, 8.0596e-01,  ..., 5.0622e-01,
           9.8651e-01, 9.3901e-01],
          [8.7209e-01, 8.9824e-01, 7.6383e-01,  ..., 5.5565e-01,
           7.8321e-04, 6.0651e-01],
          [6.5072e-01, 1.7295e-01, 6.3266e-01,  ..., 2.2064e-01,
           6.5813e-01, 7.6721e-01],
          ...,
          [5.4600e-02, 2.2498e-01, 5.2766e-01,  ..., 4.266

In [193]:
# Permuted share same memory
x_original[0, 0, 0] = 1

In [194]:
x_permuted[0, 0, 0]

tensor(1.)