<a href="https://colab.research.google.com/github/Anjasfedo/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentlas

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensors

Create Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get python int
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
print(TENSOR[0][0])

tensor([1, 2, 3])


### Random tensors

Random tensort important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data => update random numbers -> look at data -> update random numbers`

In [31]:
# Create random tensor with size of (3, 4)
rand_tensor = torch.rand(3, 4)
print(rand_tensor.shape)
print(rand_tensor.ndim)
rand_tensor

torch.Size([3, 4])
2


tensor([[0.6542, 0.4746, 0.9895, 0.6429],
        [0.6974, 0.2647, 0.9033, 0.8408],
        [0.7421, 0.1124, 0.9440, 0.5896]])

In [49]:
# Create random tensor with simmiliar shape of an image tensor
rand_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color channels(rgb))
print(rand_image_size_tensor.shape, rand_image_size_tensor.ndim)
rand_image_size_tensor

torch.Size([224, 224, 3]) 3


tensor([[[0.8711, 0.6981, 0.7530],
         [0.2311, 0.8232, 0.5726],
         [0.6015, 0.4781, 0.6783],
         ...,
         [0.1224, 0.2410, 0.8518],
         [0.9314, 0.3430, 0.4629],
         [0.6191, 0.8207, 0.4951]],

        [[0.7528, 0.2567, 0.2887],
         [0.5025, 0.6261, 0.8796],
         [0.0103, 0.9702, 0.2901],
         ...,
         [0.6931, 0.5518, 0.3827],
         [0.1531, 0.9199, 0.3197],
         [0.6165, 0.1012, 0.2895]],

        [[0.6692, 0.0863, 0.0072],
         [0.3539, 0.4017, 0.3700],
         [0.7854, 0.9747, 0.8059],
         ...,
         [0.4898, 0.4842, 0.6988],
         [0.1909, 0.6487, 0.0957],
         [0.4714, 0.3707, 0.8028]],

        ...,

        [[0.3291, 0.7294, 0.8992],
         [0.1167, 0.3838, 0.6703],
         [0.0852, 0.7706, 0.6491],
         ...,
         [0.1303, 0.6799, 0.0479],
         [0.2202, 0.8923, 0.5100],
         [0.4088, 0.1772, 0.9382]],

        [[0.0045, 0.2904, 0.1976],
         [0.7457, 0.2942, 0.9020],
         [0.

### Zeros & Ones

In [48]:
# Create tensor of all zeros
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
# Create tensor of all ones
ones_tensor = torch.ones(3, 4)
print(ones_tensor.dtype)
ones_tensor

torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensor and tensor-like

In [57]:
# Use torch.range
torch.range(0, 10)

<ipython-input-57-bfd1d11818ee>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Create tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])