<a href="https://colab.research.google.com/github/Anjasfedo/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentlas

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensors

Create Tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Get python int
scalar.item()

7

In [24]:
scalar.shape

torch.Size([])

In [13]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [36]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 3])

In [39]:
print(TENSOR[0][0])

tensor([1, 2, 3])
