# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8959, 0.3040, 0.9512, 0.8380, 0.1358, 0.2440, 0.1060],
        [0.7057, 0.3190, 0.0866, 0.8687, 0.4066, 0.8199, 0.4034],
        [0.5517, 0.1121, 0.6171, 0.6176, 0.5226, 0.7496, 0.1277],
        [0.5354, 0.5299, 0.6172, 0.1877, 0.9066, 0.6769, 0.2516],
        [0.4021, 0.3806, 0.8324, 0.1803, 0.4359, 0.2156, 0.0440],
        [0.3038, 0.5111, 0.9868, 0.4003, 0.9909, 0.0720, 0.3763],
        [0.7235, 0.7588, 0.5666, 0.7094, 0.8507, 0.6683, 0.8090]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
another_random_tensor = torch.rand(1, 7)

# Perform matrix multiplication
new_random_tensor = torch.matmul(random_tensor, another_random_tensor.T)

new_random_tensor

tensor([[1.1312],
        [1.1254],
        [0.9923],
        [1.0800],
        [0.7081],
        [1.0022],
        [1.5187]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
# Create two random tensors
first_tensor = torch.rand(7, 7)
second_tensor = torch.rand(1, 7).T

# Matrix multiply tensors
mul_tensor = torch.matmul(first_tensor, second_tensor)
mul_tensor, mul_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
device, seed = ["cuda", 1234] if torch.cuda.is_available else ["cpu", 0]

device, seed

('cuda', 1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed

# Check for access to GPU

# Create two random tensors on GPU
torch.manual_seed(seed)
first_gpu_tensor = torch.rand(2, 3).to(device)

torch.manual_seed(seed)
second_gpu_tensor = torch.rand(2, 3).to(device)

first_gpu_tensor, second_gpu_tensor

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
mul_gpu_tensor = torch.matmul(first_gpu_tensor, second_gpu_tensor.T)

mul_gpu_tensor

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
print(torch.max(mul_gpu_tensor))
# Find min
print(torch.min(mul_gpu_tensor))

tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
print(torch.argmax(mul_gpu_tensor))

# Find arg min
print(torch.argmin(mul_gpu_tensor))


tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensors = torch.rand(1, 1, 1, 10)

# Remove single dimensions
new_random_tensors = random_tensors.squeeze()

# Print out tensors and their shapes
print(random_tensors, random_tensors.shape)
print(new_random_tensors, new_random_tensors.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
